import { FeatureIcon, LanguageToggle, LocalizedText, Logo, StatusBadge } from "@powerchain/ui";

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-neutral-50"><header className="border-b border-neutral-200 bg-white"><div className="mx-auto flex h-[68px] max-w-6xl items-center justify-between px-4 sm:px-6"><Logo/><div className="flex items-center gap-2"><LanguageToggle/><a href="http://localhost:3001/explore" className="rounded-lg px-3 py-2 text-sm font-semibold text-neutral-600 transition hover:bg-neutral-100"><LocalizedText en="Explore projects" es="Explorar proyectos"/></a></div></div></header><main className="pc-grid-bg mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8 lg:py-14"><div className="grid overflow-hidden rounded-[22px] border border-neutral-200 bg-white shadow-[0_24px_70px_rgba(0,0,0,.07)] sm:rounded-[28px] lg:min-h-[620px] lg:grid-cols-[.9fr_1.1fr]"><aside className="hidden bg-emerald-950 p-10 text-white lg:flex lg:flex-col lg:justify-between"><div><StatusBadge><LocalizedText en="Secure organization access" es="Acceso seguro para organizaciones"/></StatusBadge><h1 className="mt-6 text-4xl font-bold leading-tight tracking-[-.04em]"><LocalizedText en="Operate deals and campaigns with clear roles and controlled financial permissions." es="Gestiona operaciones y campañas con roles claros y permisos financieros controlados."/></h1><p className="mt-4 text-sm leading-6 text-white/65"><LocalizedText en="Founder editing, investor diligence, evidence review, escrow approval and platform administration remain separate responsibilities." es="La edición del fundador, la debida diligencia del inversor, la revisión de evidencia, la aprobación del escrow y la administración de la plataforma permanecen como responsabilidades separadas."/></p><div className="mt-8 space-y-4">{[
          {icon:"shield" as const,title:<LocalizedText en="Role-separated access" es="Acceso separado por roles"/>,copy:<LocalizedText en="Founder, investor and treasury permissions are distinct." es="Los permisos de fundador, inversor y tesorería son distintos."/>},
          {icon:"file" as const,title:<LocalizedText en="Evidence workflow" es="Flujo de evidencia"/>,copy:<LocalizedText en="Milestone proof can be reviewed before any release." es="La prueba del hito puede revisarse antes de cualquier liberación."/>},
          {icon:"lock" as const,title:<LocalizedText en="Escrow controls" es="Controles de escrow"/>,copy:<LocalizedText en="Investor approval does not bypass treasury or on-chain policy." es="La aprobación del inversor no omite la política de tesorería ni la política on-chain."/>}
        ].map(({icon,title,copy},index)=><div key={index} className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/10"><FeatureIcon name={icon}/></span><div><div className="text-sm font-bold">{title}</div><div className="mt-1 text-xs leading-5 text-white/55">{copy}</div></div></div>)}</div></div><div className="text-xs text-white/45">PowerChain Platform v1.0.0</div></aside><section className="flex items-center justify-center p-5 sm:p-8 lg:p-10">{children}</section></div></main><footer className="border-t border-neutral-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-2 px-4 py-5 text-xs text-neutral-500 sm:flex-row sm:items-center sm:justify-between sm:px-6"><span><LocalizedText en="PowerChain secure access" es="Acceso seguro de PowerChain"/></span><span><a href="/privacy"><LocalizedText en="Privacy" es="Privacidad"/></a> · <a href="/terms"><LocalizedText en="Terms" es="Términos"/></a></span></div></footer></div>;
}
