import { AppShell, Card, MetricCard, PageHeader, Section, StatusBadge } from "@powerchain/ui";
import { TreasuryMilestoneChart } from "../components/treasury-milestone-chart";

const campaignProgress = [
  { title: "Flood Emergency Response", raised: 147200, goal: 250000, available: 84200, milestones: [{ label: "M1", target: 50000, status: "complete" as const }, { label: "M2", target: 125000, status: "next" as const }, { label: "M3", target: 190000, status: "future" as const }, { label: "M4", target: 250000, status: "future" as const }] },
  { title: "Mobile Medical Clinics", raised: 84200, goal: 120000, available: 39100, milestones: [{ label: "M1", target: 30000, status: "complete" as const }, { label: "M2", target: 70000, status: "complete" as const }, { label: "M3", target: 100000, status: "next" as const }, { label: "M4", target: 120000, status: "future" as const }] },
  { title: "Community Solar Microgrid", raised: 128500, goal: 200000, available: 76500, milestones: [{ label: "Design", target: 40000, status: "complete" as const }, { label: "Procure", target: 110000, status: "complete" as const }, { label: "Install", target: 165000, status: "next" as const }, { label: "Operate", target: 200000, status: "future" as const }] },
  { title: "Clean Energy Community Event", raised: 32800, goal: 50000, available: 26700, milestones: [{ label: "Venue", target: 12500, status: "complete" as const }, { label: "Program", target: 30000, status: "complete" as const }, { label: "Delivery", target: 45000, status: "next" as const }, { label: "Close", target: 50000, status: "future" as const }] },
];

export default function Page() {
  return <AppShell appName="Organizer Dashboard" nav={[{ label: "Campaigns", href: "/campaigns" }, { label: "Evidence", href: "/campaigns/cmp_flood/milestones/m2/evidence" }, { label: "Treasury", href: "http://localhost:3005" }, { label: "Explorer", href: "http://localhost:3007" }]}>
    <PageHeader eyebrow="Organization" title="Campaign command center" description="Funding, milestone targets, evidence gates, treasury controls and reconciliation in one operational workspace." action={<a href="http://localhost:3001/create" className="rounded-xl bg-emerald-950 px-4 py-2.5 text-sm font-bold text-white">Create campaign</a>} />
    <div className="mt-6 grid gap-4 md:grid-cols-4"><MetricCard label="Active campaigns" value="4" detail="1 emergency · 1 renewable" /><MetricCard label="Confirmed funding" value="€392,700" detail="Reconciled only" /><MetricCard label="Treasury available" value="€226,500" /><MetricCard label="Evidence gates" value="2" detail="Awaiting verification" /></div>
    <Section title="Funding & milestone readiness" description="Funding bars use reconciled treasury receipts; markers show cumulative funding thresholds for campaign milestones."><TreasuryMilestoneChart campaigns={campaignProgress} /></Section>
    <Section title="Operational attention"><div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center justify-between gap-4"><h3 className="font-bold">Flood Emergency Response · M2</h3><StatusBadge tone="warning">Evidence due</StatusBadge></div><p className="mt-2 text-sm leading-6 text-slate-600">The funding threshold is reached, but the release gate remains closed until receipts and field proof are reviewed.</p><a href="/campaigns/cmp_flood/milestones/m2/evidence" className="mt-4 inline-flex text-sm font-bold text-emerald-900">Submit and verify evidence →</a></Card><Card className="p-5"><div className="flex items-center justify-between"><h3 className="font-bold">Reconciliation queue</h3><StatusBadge tone="warning">2 review</StatusBadge></div><p className="mt-2 text-sm leading-6 text-slate-600">One unmatched reference and one amount mismatch. Campaign balances are never auto-adjusted from provider observations.</p></Card></div></Section>
  </AppShell>;
}
