import { AppShell, Card, Icon, MetricCard, PageHeader, Section, StatusBadge } from "@powerchain/ui";
import { TreasuryMilestoneChart } from "../components/treasury-milestone-chart";

const campaignProgress = [
  { title: "Flood Emergency Response", raised: 147200, goal: 250000, available: 84200, milestones: [{ label: "M1", target: 50000, status: "complete" as const }, { label: "M2", target: 125000, status: "next" as const }, { label: "M3", target: 190000, status: "future" as const }, { label: "M4", target: 250000, status: "future" as const }] },
  { title: "Mobile Medical Clinics", raised: 84200, goal: 120000, available: 39100, milestones: [{ label: "M1", target: 30000, status: "complete" as const }, { label: "M2", target: 70000, status: "complete" as const }, { label: "M3", target: 100000, status: "next" as const }, { label: "M4", target: 120000, status: "future" as const }] },
  { title: "Community Solar Microgrid", raised: 128500, goal: 200000, available: 76500, milestones: [{ label: "Design", target: 40000, status: "complete" as const }, { label: "Procure", target: 110000, status: "complete" as const }, { label: "Install", target: 165000, status: "next" as const }, { label: "Operate", target: 200000, status: "future" as const }] },
  { title: "Clean Energy Community Event", raised: 32800, goal: 50000, available: 26700, milestones: [{ label: "Venue", target: 12500, status: "complete" as const }, { label: "Program", target: 30000, status: "complete" as const }, { label: "Delivery", target: 45000, status: "next" as const }, { label: "Close", target: 50000, status: "future" as const }] },
];

export default function Page() {
  return <AppShell appName="Organizer Dashboard" notificationCount={3} nav={[{ label: "Campaigns", href: "/campaigns" }, { label: "Trust", href: "/trust" }, { label: "Agreements", href: "/agreements" }, { label: "Invoices", href: "/invoices" }, { label: "Company", href: "/settings/company" }, { label: "SaaS", href: "/settings/saas" }, { label: "Treasury", href: "http://localhost:3005" }, { label: "Explorer", href: "http://localhost:3007" }]}>
    <PageHeader eyebrow="Organization workspace" title="Campaign command center" description="Funding, milestone readiness, evidence gates, treasury controls and reconciliation—organized around the decisions your team needs to make next." action={<a href="http://localhost:3001/create" className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-950 px-4 text-sm font-bold text-white shadow-sm">Create campaign <Icon name="arrow-right"/></a>} />
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><MetricCard label="Active campaigns" value="4" detail="1 emergency · 1 renewable" trend="All healthy"/><MetricCard label="Confirmed funding" value="€392,700" detail="Reconciled contributions only" trend="+8.2%"/><MetricCard label="Treasury available" value="€226,500" detail="Across active campaign treasuries"/><MetricCard label="Evidence gates" value="2" detail="Awaiting reviewer verification"/><MetricCard label="Trust checks" value="4 / 6" detail="2 checks still require action"/></div>
    <Section title="Funding & milestone readiness" description="See which milestones have reached their funding threshold and which still require evidence or approval before funds can move."><TreasuryMilestoneChart campaigns={campaignProgress}/></Section><Section title="Capital marketplace workspace" description="Founder listings and investor diligence remain separated from humanitarian campaign workflows while sharing identity, agreements, escrow and audit infrastructure."><div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 text-emerald-950"><Icon name="briefcase"/></span><h3 className="mt-4 font-bold">Founder listing</h3><p className="mt-2 text-sm leading-6 text-neutral-600">Build a profile, team, deal terms and 3–5 milestone tranches with a derived raise goal.</p><a href="/founder/listing" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-950">Open builder <Icon name="arrow-right"/></a></Card><Card className="p-5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 text-emerald-950"><Icon name="chat"/></span><h3 className="mt-4 font-bold">Investor offers</h3><p className="mt-2 text-sm leading-6 text-neutral-600">Review investor interest and negotiate qualified offers inside participant-only deal rooms.</p><a href="/founder/offers" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-950">Review offers <Icon name="arrow-right"/></a></Card><Card className="p-5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 text-emerald-950"><Icon name="star"/></span><h3 className="mt-4 font-bold">Investor watchlist</h3><p className="mt-2 text-sm leading-6 text-neutral-600">Track matched opportunities and return to diligence or deal rooms without exposing private preference data.</p><a href="/investor/watchlist" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-950">Open watchlist <Icon name="arrow-right"/></a></Card></div></Section>
    <div className="mt-10 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section><div className="mb-5"><h2 className="text-lg font-bold tracking-tight">Operational attention</h2><p className="mt-1 text-sm text-neutral-500">Items that may block a release or need an operator decision.</p></div><div className="grid gap-4"><Card className="p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-50 text-amber-900"><Icon name="file"/></span><div><h3 className="font-bold">Flood Emergency Response · M2</h3><p className="mt-1 text-sm leading-6 text-neutral-600">Funding threshold reached. Receipts and field proof are still required before the next release.</p></div></div><StatusBadge tone="warning">Evidence due</StatusBadge></div><a href="/campaigns/cmp_flood/milestones/m2/evidence" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-950">Review evidence <Icon name="arrow-right"/></a></Card><Card className="p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-neutral-100 text-neutral-600"><Icon name="shield"/></span><div><h3 className="font-bold">Reconciliation queue</h3><p className="mt-1 text-sm leading-6 text-neutral-600">One unmatched reference and one amount mismatch. Campaign totals remain unchanged until review.</p></div></div><StatusBadge tone="warning">2 review</StatusBadge></div></Card></div></section><section><div className="mb-5"><h2 className="text-lg font-bold tracking-tight">Recent activity</h2><p className="mt-1 text-sm text-neutral-500">Latest reconciled and reviewed campaign events.</p></div><Card className="divide-y divide-neutral-200">{([["Payment reconciled","€250 EURe · Flood Emergency Response","2m ago","success"],["Evidence verified","M1 · Mobile Medical Clinics","18m ago","success"],["Disbursement proposed","€12,500 · Medical supplies","34m ago","neutral"],["Campaign updated","Community Solar Microgrid","1h ago","neutral"]] as const).map(([title,copy,time,tone])=><div key={title+time} className="flex items-start gap-3 p-4"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${tone === "success" ? "bg-emerald-700" : "bg-neutral-300"}`}/><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{title}</div><div className="mt-1 truncate text-xs text-neutral-500">{copy}</div></div><div className="text-[10px] text-neutral-400">{time}</div></div>)}</Card></section></div>
  </AppShell>;
}
