import { notFound } from "next/navigation";
import { AppShell, Card, Icon, LocalizedText, PageHeader, ProgressBar, Section, StatusBadge } from "@powerchain/ui";
import { listingFixtures, listingGoal } from "../../../lib/listings";

function money(value: number) { return new Intl.NumberFormat("en", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value); }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const listing = listingFixtures.find((item) => item.slug === slug);
  if (!listing) notFound();
  const goal = listingGoal(listing);
  const funded = listing.tranches.filter((item)=>item.status !== "FUTURE").reduce((sum,item)=>sum+item.amount,0);
  return <AppShell appName={<LocalizedText en="Due Diligence" es="Debida diligencia"/>} nav={[{label:<LocalizedText en="Marketplace" es="Mercado"/>,href:"/marketplace"},{label:<LocalizedText en="Watchlist" es="Seguimiento"/>,href:"/watchlist"}]}>
    <PageHeader eyebrow={`${listing.category} · ${listing.stage}`} title={listing.productName} description={listing.tagline} action={<div className="flex gap-2"><StatusBadge tone={listing.verified?"success":"warning"}>{listing.verified?<LocalizedText en="Business verified" es="Empresa verificada"/>:<LocalizedText en="Verification pending" es="Verificación pendiente"/>}</StatusBadge><StatusBadge tone="success">{listing.matchScore}% <LocalizedText en="match" es="coincidencia"/></StatusBadge></div>}/>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_360px]">
      <div>
        <Card className="p-6"><div className="grid gap-5 md:grid-cols-3"><div><div className="text-xs font-bold uppercase tracking-[.08em] text-neutral-500"><LocalizedText en="Derived raise" es="Objetivo derivado"/></div><div className="mt-2 text-3xl font-bold">{money(goal)}</div></div><div><div className="text-xs font-bold uppercase tracking-[.08em] text-neutral-500"><LocalizedText en="Instrument" es="Instrumento"/></div><div className="mt-2 text-lg font-bold">{listing.instrument}</div></div><div><div className="text-xs font-bold uppercase tracking-[.08em] text-neutral-500"><LocalizedText en="Location" es="Ubicación"/></div><div className="mt-2 text-lg font-bold">{listing.location}</div></div></div><div className="mt-5"><ProgressBar value={funded/goal*100}/></div><div className="mt-2 text-xs text-neutral-500">{money(funded)} <LocalizedText en="funded / reserved across milestone tranches" es="financiado / reservado entre tramos por hitos"/></div></Card>
        <Section title={<LocalizedText en="Milestone raise" es="Ronda por hitos"/>} description={<LocalizedText en="The raise target is the exact sum of 3–5 tranche amounts; founders do not type an independent funding goal." es="El objetivo de la ronda es la suma exacta de 3–5 tramos; el fundador no introduce un objetivo de financiación independiente."/>}><div className="grid gap-3">{listing.tranches.map((tranche,index)=><Card key={tranche.id} className="p-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div className="flex gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 text-sm font-bold text-emerald-950">{index+1}</span><div><h3 className="font-bold">{tranche.title}</h3><p className="mt-1 text-sm text-neutral-500"><LocalizedText en="Proof" es="Prueba"/>: {tranche.proof}</p></div></div><div className="text-right"><div className="font-bold">{money(tranche.amount)}</div><StatusBadge tone={tranche.status==="RELEASED"?"success":tranche.status==="APPROVED"?"success":tranche.status==="FUNDED"?"warning":"neutral"}>{tranche.status.toLowerCase()}</StatusBadge></div></div></Card>)}</div></Section>
        <Section title={<LocalizedText en="Team" es="Equipo"/>}><div className="grid gap-4 md:grid-cols-2">{listing.team.map((member)=><Card key={member.name} className="p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-neutral-100 text-neutral-600"><Icon name="users"/></span><div><h3 className="font-bold">{member.name}</h3><div className="text-xs font-semibold text-emerald-900">{member.role}</div><p className="mt-2 text-sm leading-6 text-neutral-600">{member.bio}</p></div></div></Card>)}</div></Section>
        <Section title={<LocalizedText en="Traction & diligence" es="Tracción y diligencia"/>}><div className="grid gap-4 md:grid-cols-2"><Card className="p-5"><h3 className="font-bold"><LocalizedText en="Operating evidence" es="Evidencia operativa"/></h3><ul className="mt-3 space-y-2 text-sm text-neutral-600">{listing.traction.map((item)=><li key={item} className="flex gap-2"><Icon name="check" className="mt-0.5 h-4 w-4 text-emerald-800"/>{item}</li>)}</ul></Card><Card className="p-5"><h3 className="font-bold"><LocalizedText en="Disclosed risks" es="Riesgos divulgados"/></h3><ul className="mt-3 space-y-2 text-sm text-neutral-600">{listing.risks.map((item)=><li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-amber-600"/>{item}</li>)}</ul></Card></div></Section>
      </div>
      <aside className="space-y-4 xl:sticky xl:top-24 xl:self-start"><Card className="p-5"><h2 className="font-bold"><LocalizedText en="Deal room" es="Sala de negociación"/></h2><p className="mt-2 text-sm leading-6 text-neutral-600"><LocalizedText en="Discuss terms, exchange diligence files and review offers with authenticated participants." es="Negocia términos, intercambia archivos de diligencia y revisa ofertas con participantes autenticados."/></p><div className="mt-4 grid gap-2"><a href={`/deal-room/room_${listing.id}`} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-emerald-950 text-sm font-bold text-white"><Icon name="chat"/> <LocalizedText en="Express interest" es="Mostrar interés"/></a><a href={`/deal-room/room_${listing.id}?offer=1`} className="inline-flex h-11 items-center justify-center rounded-xl border bg-white text-sm font-bold"><LocalizedText en="Make an offer" es="Hacer una oferta"/></a></div></Card><Card className="p-5"><h3 className="font-bold"><LocalizedText en="Diligence files" es="Archivos de diligencia"/></h3><div className="mt-3 grid gap-2"><a href={listing.pitchDeckUrl} className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold"><Icon name="file"/> <LocalizedText en="Pitch deck" es="Presentación"/></a><a href={listing.demoVideoUrl} className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold"><Icon name="video"/> <LocalizedText en="Demo video" es="Video demo"/></a></div><p className="mt-3 text-[11px] leading-5 text-neutral-500"><LocalizedText en="Example URLs in mock data are not production diligence documents." es="Las URL de ejemplo en los datos simulados no son documentos de diligencia de producción."/></p></Card><Card className="p-5"><h3 className="font-bold"><LocalizedText en="Trust checks" es="Verificaciones de confianza"/></h3><div className="mt-3 space-y-2">{([["Founder identity","Identidad del fundador"],["Business registry","Registro mercantil"],["Beneficial ownership","Titularidad real"],["Treasury control","Control de tesorería"]] as const).map(([en,es])=><div key={en} className="flex items-center justify-between text-sm"><span><LocalizedText en={en} es={es}/></span><StatusBadge tone={listing.verified?"success":"warning"}>{listing.verified?<LocalizedText en="Verified" es="Verificado"/>:<LocalizedText en="Review" es="Revisión"/>}</StatusBadge></div>)}</div></Card></aside>
    </div>
  </AppShell>;
}
