"use client";
import {useState} from "react";
import {Button,Card,StatusBadge} from "@powerchain/ui";

type CheckoutResult={kind:"REDIRECT";provider:"MIDTRANS";url:string;orderId:string}|{kind:"CONTACT_SUPPORT";provider:"DEMO";message:string;orderId:string};
export function DonationPanel({campaignId}:{campaignId:string}){
 const [amount,setAmount]=useState(50); const [loading,setLoading]=useState(false); const [support,setSupport]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
 async function donate(){setLoading(true);setError(null);try{const base=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"";const r=await fetch(`${base}/api/v1/funding/checkout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({campaignId,amount})});const body=await r.json();if(!r.ok)throw new Error(body?.error?.message??`Checkout failed with HTTP ${r.status}`);const result=body.data as CheckoutResult;if(result.kind==="REDIRECT")window.location.assign(result.url);else setSupport(result.message)}catch(e){setError(e instanceof Error?e.message:"Checkout unavailable")}finally{setLoading(false)}}
 return <Card className="p-5"><div className="flex items-center justify-between"><div className="font-bold">Support this campaign</div><StatusBadge tone="success">Escrowed</StatusBadge></div><div className="mt-4 grid grid-cols-4 gap-2">{[25,50,100,250].map(v=><button key={v} onClick={()=>setAmount(v)} className={`rounded-xl border px-2 py-2 text-sm font-bold ${amount===v?"border-emerald-900 bg-emerald-50 text-emerald-950":"bg-white"}`}>€{v}</button>)}</div><Button onClick={()=>void donate()} disabled={loading} className="mt-4 w-full">{loading?"Preparing checkout…":`Donate €${amount}`}</Button><p className="mt-3 text-[11px] leading-5 text-neutral-500">Hosted Midtrans checkout is used when enabled. In demo mode PowerChain opens support guidance instead of marking a fake payment as successful.</p>{error?<div className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-800">{error}</div>:null}{support?<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="text-sm font-bold text-amber-950">Payment demo mode</div><p className="mt-1 text-xs leading-5 text-amber-900">{support}</p><button onClick={()=>setSupport(null)} className="mt-3 text-xs font-bold text-amber-950">Close</button></div>:null}</Card>
}
