"use client";

import { useState } from "react";
import { Card, Icon, StatusBadge, useLocale } from "@powerchain/ui";

export function MilestoneEscrowReview({ escrowId, trancheId }: { escrowId: string; trancheId: string }) {
  const { locale } = useLocale();
  const es = locale === "es";
  const [approvalState, setApprovalState] = useState<"READY" | "SUBMITTING" | "UNAVAILABLE">("READY");
  const [claimState, setClaimState] = useState<"BLOCKED" | "READY" | "SUBMITTING" | "UNAVAILABLE">("BLOCKED");

  const approve = async () => {
    setApprovalState("SUBMITTING");
    const response = await fetch(`/api/v1/escrows/${encodeURIComponent(escrowId)}/tranches/${encodeURIComponent(trancheId)}/approve-proof`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ proofId: "proof_7a91" }) }).catch(() => null);
    if (!response?.ok) { setApprovalState("UNAVAILABLE"); return; }
    setApprovalState("READY"); setClaimState("READY");
  };

  const claim = async () => {
    setClaimState("SUBMITTING");
    const response = await fetch(`/api/v1/campaigns/lst_solarflow/milestones/${encodeURIComponent(trancheId)}/claim`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ipfsUri: "ipfs://bafybeigdyrzt5exampleproofcommitment", proofSha256: "7f83b1657ff1fc53b92dc18148a1d65dfa13514a8f92c7f0f0f0f0f0f0f0f0f0" }) }).catch(() => null);
    if (!response?.ok) { setClaimState("UNAVAILABLE"); return; }
    setClaimState("READY");
  };

  return <div className="grid gap-5 xl:grid-cols-[1fr_340px]">
    <div className="space-y-5">
      <Card className="p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold">{es ? "Tramo 2 · Despliegue piloto" : "Tranche 2 · Pilot deployment"}</h2><StatusBadge tone="warning">{es ? "Prueba en revisión" : "Proof under review"}</StatusBadge></div><p className="mt-2 max-w-2xl text-sm leading-6 text-neutral-600">{es ? "Condición de liberación: piloto instalado y aceptado por el cliente, fotografías de puesta en marcha adjuntas y aceptación firmada cargada." : "Release condition: installed pilot accepted by the customer, commissioning photos attached and signed acceptance uploaded."}</p></div><div className="text-right"><div className="text-2xl font-bold">€175,000</div><div className="mt-1 text-xs text-neutral-500">{es ? "Escrow financiado" : "Funded escrow"}</div></div></div><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-2xl bg-neutral-50 p-4"><div className="text-xs font-bold uppercase tracking-[.08em] text-neutral-500">{es ? "Tramo bruto" : "Gross tranche"}</div><div className="mt-2 font-bold">€175,000</div></div><div className="rounded-2xl bg-neutral-50 p-4"><div className="text-xs font-bold uppercase tracking-[.08em] text-neutral-500">{es ? "Comisión fijada" : "Fee snapshot"}</div><div className="mt-2 font-bold">2.50% · €4,375</div></div><div className="rounded-2xl bg-neutral-50 p-4"><div className="text-xs font-bold uppercase tracking-[.08em] text-neutral-500">{es ? "Liberación neta" : "Net release"}</div><div className="mt-2 font-bold">€170,625</div></div></div><p className="mt-4 text-xs leading-5 text-neutral-500">{es ? "La comisión queda fijada cuando el tramo se financia; una configuración posterior no puede reescribir este escrow financiado." : "The fee snapshot is fixed when the tranche becomes funded; later platform-fee configuration cannot rewrite this funded escrow."}</p></Card>
      <Card className="p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-950"><Icon name="file-check"/></span><div><h2 className="font-bold">{es ? "Prueba del hito" : "Milestone proof"}</h2><p className="mt-1 text-sm text-neutral-500">{es ? "Paquete de prueba enviado por el fundador y vinculado a un compromiso de contenido." : "Founder-submitted proof bundle bound to a content commitment."}</p></div></div><dl className="mt-5 grid grid-cols-[150px_1fr] gap-y-3 text-sm"><dt className="text-neutral-500">IPFS URI</dt><dd className="break-all font-mono text-xs">ipfs://bafybeigdyrzt5exampleproofcommitment</dd><dt className="text-neutral-500">SHA-256</dt><dd className="break-all font-mono text-xs">7f83b1657ff1fc53…f0f0f0f0</dd><dt className="text-neutral-500">{es ? "Enviado" : "Submitted"}</dt><dd>19 Aug 2026 · 04:42</dd><dt className="text-neutral-500">{es ? "Evidencia" : "Evidence"}</dt><dd>Acceptance PDF · 4 photos · commissioning report</dd></dl><div className="mt-5 flex flex-wrap gap-2"><button type="button" className="inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><Icon name="eye"/> {es ? "Revisar evidencia" : "Review evidence"}</button><button type="button" onClick={()=>void approve()} disabled={approvalState==="SUBMITTING"} className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-950 px-4 text-sm font-bold text-white disabled:opacity-50"><Icon name="check"/> {approvalState==="SUBMITTING"?(es ? "Aprobando…" : "Approving…"):(es ? "Inversor: aprobar prueba" : "Investor: approve proof")}</button></div>{approvalState==="UNAVAILABLE"?<p className="mt-3 text-xs text-amber-800">{es ? "La aprobación permanece bloqueada hasta configurar la pertenencia autenticada del inversor, la persistencia de base de datos y el registro de auditoría." : "Approval is fail-closed until authenticated investor membership, database persistence and the audit sink are configured."}</p>:null}</Card>
    </div>
    <aside className="space-y-4"><Card className="p-5"><h3 className="font-bold">{es ? "Controles de liberación" : "Release gates"}</h3><div className="mt-4 space-y-3">{[[es?"Escrow financiado":"Escrow funded",true],[es?"Empresa verificada":"Business verified",true],[es?"Acuerdo totalmente firmado":"Agreement fully signed",true],[es?"Compromiso de prueba presente":"Proof commitment present",true],[es?"Aprobación de prueba del inversor":"Investor proof approval",claimState!=="BLOCKED"],[es?"Tramo no cobrado":"Tranche unclaimed",true]].map(([label,ok])=><div key={String(label)} className="flex items-center justify-between text-sm"><span>{String(label)}</span><StatusBadge tone={ok?"success":"warning"}>{ok?(es?"Listo":"Ready"):(es?"Necesario":"Required")}</StatusBadge></div>)}</div></Card><Card className="p-5"><h3 className="font-bold">{es ? "Cobro del fundador" : "Founder claim"}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{es ? <>Tras la aprobación, el fundador prepara <code>claim_milestone</code>. El propietario firma la transacción de Solana; la API no posee una clave de firma sin restricciones.</> : <>After approval, the founder prepares <code>claim_milestone</code>. The owner signs the Solana transaction; the API does not hold an unrestricted signing key.</>}</p><button type="button" disabled={claimState==="BLOCKED"||claimState==="SUBMITTING"} onClick={()=>void claim()} className="mt-4 h-11 w-full rounded-xl bg-emerald-950 text-sm font-bold text-white disabled:opacity-40">{claimState==="SUBMITTING"?(es ? "Preparando…" : "Preparing…"):(es ? "Preparar claim_milestone" : "Prepare claim_milestone")}</button>{claimState==="UNAVAILABLE"?<p className="mt-3 text-xs text-amber-800">{es ? "Se requiere un despliegue verificado del programa Solana milestone-escrow antes de habilitar la preparación del cobro." : "A verified Solana milestone-escrow program deployment is required before claim preparation is enabled."}</p>:null}</Card></aside>
  </div>;
}
