"use client";

import { useMemo, useState } from "react";
import { Card, Icon, Input, Select, StatusBadge, Textarea } from "@powerchain/ui";
import { useLocale } from "@powerchain/ui/locale-provider";

type Tranche = { id: string; title: string; amount: string; proof: string };
type TeamMember = { id: string; name: string; role: string; bio: string };

function parseAmount(value: string): number {
  const n = Number(value.replace(/[^0-9.]/g, ""));
  return Number.isFinite(n) && n > 0 ? n : 0;
}

export function FounderListingBuilder() {
  const { locale } = useLocale();
  const es = locale === "es";
  const [productName, setProductName] = useState("");
  const [tagline, setTagline] = useState("");
  const [pitchDeckUrl, setPitchDeckUrl] = useState("");
  const [demoVideoUrl, setDemoVideoUrl] = useState("");
  const [instrument, setInstrument] = useState("EQUITY");
  const [platformFeeBps] = useState(250);
  const [tranches, setTranches] = useState<Tranche[]>([
    { id: crypto.randomUUID(), title: "", amount: "", proof: "" },
    { id: crypto.randomUUID(), title: "", amount: "", proof: "" },
    { id: crypto.randomUUID(), title: "", amount: "", proof: "" },
  ]);
  const [team, setTeam] = useState<TeamMember[]>([{ id: crypto.randomUUID(), name: "", role: "", bio: "" }]);

  const goal = useMemo(() => tranches.reduce((sum, tranche) => sum + parseAmount(tranche.amount), 0), [tranches]);
  const validTrancheCount = tranches.length >= 3 && tranches.length <= 5;
  const completeTranches = tranches.every((tranche) => tranche.title.trim() && parseAmount(tranche.amount) > 0 && tranche.proof.trim());
  const canContinue = Boolean(productName.trim() && tagline.trim() && pitchDeckUrl.trim() && demoVideoUrl.trim() && validTrancheCount && completeTranches);

  const updateTranche = (id: string, patch: Partial<Tranche>) => setTranches((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const updateMember = (id: string, patch: Partial<TeamMember>) => setTeam((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));

  return <div className="grid gap-6 xl:grid-cols-[1fr_330px]">
    <div className="space-y-6">
      <Card className="p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-950"><Icon name="briefcase"/></span><div><h2 className="font-bold">{es ? "Perfil del producto" : "Product profile"}</h2><p className="mt-1 text-sm text-neutral-500">{es ? "Explica el producto antes de definir los términos de la ronda." : "Explain the product before defining the raise terms."}</p></div></div><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-semibold">{es ? "Nombre del producto" : "Product name"}<Input value={productName} onChange={(event)=>setProductName(event.target.value)} placeholder="SolarFlow Grid"/></label><label className="grid gap-2 text-sm font-semibold">{es ? "Propuesta breve" : "One-line pitch"}<Input value={tagline} onChange={(event)=>setTagline(event.target.value)} placeholder={es ? "Qué haces y para quién" : "What you build and for whom"}/></label><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">{es ? "URL de la presentación" : "Pitch deck URL"}<Input type="url" value={pitchDeckUrl} onChange={(event)=>setPitchDeckUrl(event.target.value)} placeholder="https://…/deck.pdf"/></label><label className="grid gap-2 text-sm font-semibold">{es ? "URL del video demo" : "Demo video URL"}<Input type="url" value={demoVideoUrl} onChange={(event)=>setDemoVideoUrl(event.target.value)} placeholder="https://…/demo"/></label></div></div></Card>
      <Card className="p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold">{es ? "Tramos por hitos" : "Milestone tranches"}</h2><p className="mt-1 text-sm text-neutral-500">{es ? "Configura entre 3 y 5 tramos. El objetivo se calcula automáticamente." : "Define 3–5 tranches. The raise goal is derived automatically."}</p></div><StatusBadge tone={validTrancheCount?"success":"warning"}>{tranches.length} / 3–5</StatusBadge></div><div className="mt-5 space-y-4">{tranches.map((tranche,index)=><div key={tranche.id} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4"><div className="mb-3 flex items-center justify-between"><div className="font-bold">{es ? "Tramo" : "Tranche"} {index+1}</div>{tranches.length>3?<button type="button" onClick={()=>setTranches((items)=>items.filter((item)=>item.id!==tranche.id))} className="text-xs font-semibold text-red-700">{es ? "Eliminar" : "Remove"}</button>:null}</div><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1.5 text-xs font-semibold">{es ? "Hito" : "Milestone"}<Input value={tranche.title} onChange={(event)=>updateTranche(tranche.id,{title:event.target.value})} placeholder={es ? "Ej. Despliegue piloto" : "e.g. Pilot deployment"}/></label><label className="grid gap-1.5 text-xs font-semibold">{es ? "Importe EUR" : "Amount EUR"}<Input inputMode="decimal" value={tranche.amount} onChange={(event)=>updateTranche(tranche.id,{amount:event.target.value})} placeholder="125000"/></label></div><label className="mt-3 grid gap-1.5 text-xs font-semibold">{es ? "Prueba necesaria para liberar" : "Proof required for release"}<Input value={tranche.proof} onChange={(event)=>updateTranche(tranche.id,{proof:event.target.value})} placeholder={es ? "Informe, aceptación, enlace IPFS…" : "Report, acceptance, IPFS proof…"}/></label></div>)}</div>{tranches.length<5?<button type="button" onClick={()=>setTranches((items)=>[...items,{id:crypto.randomUUID(),title:"",amount:"",proof:""}])} className="mt-4 inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><span>+</span>{es ? "Añadir tramo" : "Add tranche"}</button>:null}</Card>
      <Card className="p-6"><h2 className="font-bold">{es ? "Equipo" : "Team"}</h2><div className="mt-4 space-y-4">{team.map((member)=><div key={member.id} className="rounded-2xl border p-4"><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1.5 text-xs font-semibold">{es ? "Nombre" : "Name"}<Input value={member.name} onChange={(event)=>updateMember(member.id,{name:event.target.value})}/></label><label className="grid gap-1.5 text-xs font-semibold">{es ? "Cargo" : "Role"}<Input value={member.role} onChange={(event)=>updateMember(member.id,{role:event.target.value})}/></label></div><label className="mt-3 grid gap-1.5 text-xs font-semibold">Bio<Textarea value={member.bio} onChange={(event)=>updateMember(member.id,{bio:event.target.value})}/></label></div>)}</div><button type="button" onClick={()=>setTeam((items)=>[...items,{id:crypto.randomUUID(),name:"",role:"",bio:""}])} className="mt-4 inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><span>+</span>{es ? "Añadir miembro" : "Add team member"}</button></Card>
      <Card className="p-6"><h2 className="font-bold">{es ? "Términos de la operación" : "Deal terms"}</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">{es ? "Instrumento" : "Instrument"}<Select value={instrument} onChange={(event)=>setInstrument(event.target.value)}><option value="EQUITY">Equity</option><option value="SAFE_NOTE">SAFE note</option><option value="CONVERTIBLE_NOTE">Convertible note</option><option value="REVENUE_BASED">Revenue based</option><option value="OTHER">Other</option></Select></label><label className="grid gap-2 text-sm font-semibold">{es ? "Comisión de plataforma" : "Platform fee"}<Input value={`${(platformFeeBps/100).toFixed(2)}%`} readOnly/></label></div><p className="mt-3 text-xs leading-5 text-neutral-500">{es ? "La comisión se congela cuando el escrow se financia y no puede modificarse para ese escrow financiado." : "The fee is snapshotted when escrow is funded and cannot be changed for that funded escrow."}</p></Card>
    </div>
    <aside className="space-y-4 xl:sticky xl:top-24 xl:self-start"><Card className="p-5"><div className="text-xs font-bold uppercase tracking-[.1em] text-neutral-500">{es ? "Objetivo derivado" : "Derived raise goal"}</div><div className="mt-2 text-4xl font-bold tracking-tight">€{goal.toLocaleString()}</div><p className="mt-2 text-xs leading-5 text-neutral-500">{es ? "Suma exacta de los tramos configurados." : "Exact sum of configured tranches."}</p><div className="mt-4 space-y-2">{tranches.map((tranche,index)=><div key={tranche.id} className="flex items-center justify-between text-xs"><span>{index+1}. {tranche.title || (es ? "Sin título" : "Untitled")}</span><span className="font-semibold">€{parseAmount(tranche.amount).toLocaleString()}</span></div>)}</div></Card><Card className="p-5"><h3 className="font-bold">{es ? "Preparación" : "Readiness"}</h3><div className="mt-3 space-y-2 text-sm">{[[Boolean(productName&&tagline),es?"Perfil":"Profile"],[Boolean(pitchDeckUrl&&demoVideoUrl),es?"Materiales":"Materials"],[completeTranches,es?"Tramos y pruebas":"Tranches & proof"],[team.some((member)=>member.name&&member.role),es?"Equipo":"Team"]].map(([ok,label])=><div key={String(label)} className="flex items-center justify-between"><span>{String(label)}</span><StatusBadge tone={ok?"success":"warning"}>{ok?(es?"Listo":"Ready"):(es?"Falta":"Missing")}</StatusBadge></div>)}</div></Card><button type="button" disabled={!canContinue} className="h-12 w-full rounded-xl bg-emerald-950 text-sm font-bold text-white disabled:opacity-40">{es ? "Continuar a verificación" : "Continue to verification"}</button><p className="text-[11px] leading-5 text-neutral-500">{es ? "Enviar una ficha de fundador no la convierte por sí sola en una oferta legalmente conforme. La jurisdicción, elegibilidad del inversor y términos aprobados por asesoría legal siguen siendo necesarios antes de aceptar inversión en vivo." : "Submitting a founder listing does not make it a legally compliant offering. Jurisdiction, investor eligibility and counsel-approved terms remain required before live investment acceptance."}</p></aside>
  </div>;
}
