import type { Invoice, InvoiceLineItem, InvoiceTotals } from "@powerchain/types";

function money(value: string | number, currency: string) {
  const number = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(number)) return `${value} ${currency}`;
  return new Intl.NumberFormat("en", { style: "currency", currency, minimumFractionDigits: 2 }).format(number);
}

function lineNet(line: InvoiceLineItem): number {
  return Number(line.quantity || "0") * Number(line.unitPrice || "0");
}

export function calculateInvoiceTotals(invoice: Invoice): InvoiceTotals {
  const subtotal = invoice.lines.reduce((sum, line) => sum + lineNet(line), 0);
  const tax = invoice.lines.reduce((sum, line) => sum + lineNet(line) * (line.taxRateBps / 10_000), 0);
  const fees = invoice.fees.reduce((sum, fee) => sum + Number(fee.amount || "0"), 0);
  const discount = Number(invoice.discountAmount || "0");
  const total = subtotal + tax + fees - discount;
  return { subtotal: subtotal.toFixed(2), tax: tax.toFixed(2), fees: fees.toFixed(2), discount: discount.toFixed(2), total: total.toFixed(2) };
}

function Party({ label, party }: { label: string; party: Invoice["issuer"] }) {
  return <div><div className="text-[10px] font-bold uppercase tracking-[0.18em] text-neutral-400">{label}</div><div className="mt-2 font-bold text-neutral-950 dark:text-white">{party.tradingName || party.name}</div>{party.tradingName && party.tradingName !== party.name ? <div className="mt-0.5 text-xs text-neutral-500">{party.name}</div> : null}<div className="mt-2 space-y-0.5 text-xs leading-5 text-neutral-500">{party.address ? <><div>{party.address.line1}</div>{party.address.line2 ? <div>{party.address.line2}</div> : null}<div>{party.address.postalCode} {party.address.city}</div><div>{party.address.countryCode}</div></> : null}{party.registrationNumber ? <div>Reg. {party.registrationNumber}</div> : null}{party.foundationNumber ? <div>Foundation {party.foundationNumber}</div> : null}{party.taxId ? <div>Tax/VAT {party.taxId}</div> : null}{party.email ? <div>{party.email}</div> : null}</div></div>;
}

export function PowerChainInvoice({ invoice, compact = false }: { invoice: Invoice; compact?: boolean }) {
  const totals = calculateInvoiceTotals(invoice);
  return <article className="overflow-hidden rounded-[28px] border border-neutral-200 bg-white text-neutral-900 shadow-[0_24px_80px_-40px_rgba(0,0,0,0.32)] dark:border-neutral-800 dark:bg-neutral-950 dark:text-neutral-100">
    <header className="border-b border-neutral-200 bg-gradient-to-br from-emerald-950 via-emerald-900 to-neutral-950 p-6 text-white sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-3">{invoice.issuer.logoUrl ? <img src={invoice.issuer.logoUrl} alt="" className="h-12 w-12 rounded-2xl bg-white object-contain p-1.5"/> : <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-sm font-black">PC</div>}<div><div className="text-lg font-extrabold tracking-tight">{invoice.issuer.tradingName || invoice.issuer.name}</div><div className="mt-1 text-xs text-emerald-100">PowerChain Invoice</div></div></div><div className="sm:text-right"><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-emerald-200">Invoice</div><div className="mt-1 font-mono text-xl font-bold">{invoice.number}</div><div className="mt-2 inline-flex rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide">{invoice.status.replaceAll("_", " ")}</div></div></div></header>
    <div className={compact ? "p-5" : "p-6 sm:p-8"}>
      <div className="grid gap-7 sm:grid-cols-2"><Party label="From" party={invoice.issuer}/><Party label="Bill to" party={invoice.customer}/></div>
      <div className="mt-7 grid gap-3 rounded-2xl bg-neutral-50 p-4 text-xs sm:grid-cols-4 dark:bg-neutral-900"><div><div className="text-neutral-400">Issue date</div><div className="mt-1 font-semibold">{invoice.issuedAt}</div></div><div><div className="text-neutral-400">Due date</div><div className="mt-1 font-semibold">{invoice.dueAt}</div></div><div><div className="text-neutral-400">Currency</div><div className="mt-1 font-semibold">{invoice.currency}</div></div><div><div className="text-neutral-400">Reference</div><div className="mt-1 font-mono font-semibold">{invoice.settlement?.paymentReference ?? "—"}</div></div></div>
      <div className="mt-7 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-neutral-200 text-[10px] uppercase tracking-[0.14em] text-neutral-400 dark:border-neutral-800"><th className="pb-3 font-bold">Description</th><th className="pb-3 text-right font-bold">Qty</th><th className="pb-3 text-right font-bold">Unit</th><th className="pb-3 text-right font-bold">Tax</th><th className="pb-3 text-right font-bold">Amount</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.id} className="border-b border-neutral-100 dark:border-neutral-900"><td className="py-4 pr-4 font-medium">{line.description}</td><td className="py-4 text-right tabular-nums">{line.quantity}</td><td className="py-4 text-right tabular-nums">{money(line.unitPrice, invoice.currency)}</td><td className="py-4 text-right tabular-nums">{(line.taxRateBps / 100).toFixed(2)}%</td><td className="py-4 text-right font-semibold tabular-nums">{money(lineNet(line), invoice.currency)}</td></tr>)}</tbody></table></div>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_300px]"><div className="space-y-4">{invoice.notes ? <div><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-neutral-400">Notes</div><p className="mt-2 text-xs leading-6 text-neutral-500">{invoice.notes}</p></div> : null}{invoice.settlement ? <div className="rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4 text-xs dark:border-emerald-900/60 dark:bg-emerald-950/20"><div className="font-bold text-emerald-950 dark:text-emerald-200">Settlement instructions</div><div className="mt-2 grid gap-1 text-emerald-900/80 dark:text-emerald-300"><span>Rail: {invoice.settlement.rail.replaceAll("_", " ")}</span>{invoice.settlement.asset ? <span>Asset: {invoice.settlement.asset}</span> : null}{invoice.settlement.ibanMasked ? <span>IBAN: {invoice.settlement.ibanMasked}</span> : null}{invoice.settlement.treasuryAddress ? <span className="break-all font-mono">Treasury: {invoice.settlement.treasuryAddress}</span> : null}</div></div> : null}</div><div className="rounded-2xl bg-neutral-950 p-5 text-white"><div className="space-y-2 text-xs"><div className="flex justify-between"><span className="text-neutral-400">Subtotal</span><span>{money(totals.subtotal, invoice.currency)}</span></div><div className="flex justify-between"><span className="text-neutral-400">Tax</span><span>{money(totals.tax, invoice.currency)}</span></div>{Number(totals.fees) !== 0 ? <div className="flex justify-between"><span className="text-neutral-400">Fees</span><span>{money(totals.fees, invoice.currency)}</span></div> : null}{Number(totals.discount) !== 0 ? <div className="flex justify-between"><span className="text-neutral-400">Discount</span><span>-{money(totals.discount, invoice.currency)}</span></div> : null}</div><div className="mt-4 flex items-end justify-between border-t border-white/10 pt-4"><span className="text-xs font-bold uppercase tracking-[0.14em] text-neutral-400">Total</span><span className="text-2xl font-black tracking-tight">{money(totals.total, invoice.currency)}</span></div></div></div>
      <footer className="mt-7 flex flex-col gap-2 border-t border-neutral-100 pt-5 text-[10px] leading-5 text-neutral-400 sm:flex-row sm:items-center sm:justify-between dark:border-neutral-900"><span>{invoice.paymentTerms ? `Payment terms: ${invoice.paymentTerms}` : "PowerChain invoice"}</span><span className="font-mono">{invoice.auditHash ?? "Draft · audit hash assigned on issue"}</span></footer>
    </div>
  </article>;
}
