import { Card, Icon, StatusBadge } from "@powerchain/ui";

type Milestone = { label: string; target: number; status: "complete" | "next" | "future" };
type CampaignProgress = { title: string; raised: number; goal: number; available: number; milestones: Milestone[] };

const euro = new Intl.NumberFormat("en", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });

export function TreasuryMilestoneChart({ campaigns }: { campaigns: CampaignProgress[] }) {
  const totalRaised = campaigns.reduce((sum, campaign) => sum + campaign.raised, 0);
  const totalGoal = campaigns.reduce((sum, campaign) => sum + campaign.goal, 0);
  const overall = totalGoal ? Math.round(totalRaised / totalGoal * 100) : 0;
  return <Card className="overflow-hidden">
    <div className="border-b border-neutral-200 p-5 sm:p-6">
      <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 text-emerald-950"><Icon name="chart" className="h-4.5 w-4.5"/></span><div><h3 className="font-bold tracking-tight">Treasury funding vs. milestone targets</h3><p className="mt-1 text-xs leading-5 text-neutral-500">Reconciled funding is compared with cumulative milestone thresholds. Reaching a threshold does not unlock funds by itself.</p></div></div></div><div className="grid grid-cols-3 gap-2"><div className="rounded-xl bg-neutral-50 px-3 py-2"><div className="text-[10px] font-bold uppercase tracking-wide text-neutral-400">Portfolio</div><div className="mt-1 text-sm font-bold">{euro.format(totalRaised)}</div></div><div className="rounded-xl bg-neutral-50 px-3 py-2"><div className="text-[10px] font-bold uppercase tracking-wide text-neutral-400">Target</div><div className="mt-1 text-sm font-bold">{euro.format(totalGoal)}</div></div><div className="rounded-xl bg-emerald-50 px-3 py-2"><div className="text-[10px] font-bold uppercase tracking-wide text-emerald-800">Progress</div><div className="mt-1 text-sm font-bold text-emerald-950">{overall}%</div></div></div></div>
      <div className="mt-5 flex flex-wrap gap-4 text-[11px] font-medium text-neutral-500"><span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-emerald-950"/>Reconciled funding</span><span className="flex items-center gap-1.5"><span className="h-3 w-px bg-emerald-700"/>Threshold reached</span><span className="flex items-center gap-1.5"><span className="h-3 w-px bg-amber-600"/>Next threshold</span><span className="flex items-center gap-1.5"><span className="h-3 w-px bg-neutral-300"/>Future milestone</span></div>
    </div>
    <div className="divide-y divide-neutral-200">{campaigns.map((campaign) => {
      const pct = Math.min(100, campaign.goal > 0 ? campaign.raised / campaign.goal * 100 : 0);
      const next = campaign.milestones.find((milestone) => milestone.status === "next");
      const remaining = next ? Math.max(0, next.target - campaign.raised) : Math.max(0, campaign.goal - campaign.raised);
      return <div key={campaign.title} className="p-5 transition hover:bg-neutral-50 sm:p-6"><div className="grid gap-5 xl:grid-cols-[260px_1fr] xl:items-center"><div><div className="flex items-start justify-between gap-3 xl:block"><div><div className="font-semibold tracking-tight">{campaign.title}</div><div className="mt-1 text-xs text-neutral-500">{euro.format(campaign.raised)} reconciled · {euro.format(campaign.available)} available</div></div><StatusBadge tone={pct >= 100 ? "success" : pct >= 50 ? "neutral" : "warning"}>{Math.round(pct)}%</StatusBadge></div><div className="mt-3 text-[11px] font-medium text-neutral-500">{next ? `${euro.format(remaining)} to ${next.label}` : `${euro.format(remaining)} to campaign target`}</div></div><div><div className="relative pb-10" role="img" aria-label={`${campaign.title}: ${euro.format(campaign.raised)} of ${euro.format(campaign.goal)} reconciled`}><div className="h-3 overflow-hidden rounded-full bg-neutral-100"><div className="h-full rounded-full bg-emerald-950" style={{ width: `${pct}%` }}/></div>{campaign.milestones.map((milestone) => { const position = Math.min(100, campaign.goal > 0 ? milestone.target / campaign.goal * 100 : 0); return <div key={milestone.label} className="absolute top-[-5px]" style={{ left: `${position}%`, transform: "translateX(-50%)" }}><div className={`mx-auto h-6 w-px ${milestone.status === "complete" ? "bg-emerald-700" : milestone.status === "next" ? "bg-amber-600" : "bg-neutral-300"}`}/><div className={`mt-1 whitespace-nowrap text-center text-[10px] font-bold ${milestone.status === "next" ? "text-amber-800" : milestone.status === "complete" ? "text-emerald-900" : "text-neutral-400"}`}>{milestone.label}</div><div className="whitespace-nowrap text-center text-[9px] text-neutral-400">{euro.format(milestone.target)}</div></div>})}</div><div className="mt-1 flex justify-between text-[10px] text-neutral-400"><span>€0</span><span>{euro.format(campaign.goal)} target</span></div></div></div></div>;
    })}</div>
  </Card>;
}
