"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Button, Card, Icon, Input, StatusBadge, useWalletPreferences } from "@powerchain/ui";

type Tab="profile"|"account"|"connections"|"rpc"|"privacy";
const tabs: Array<{id:Tab;label:string;icon:"users"|"settings"|"link"|"globe"|"shield"}>=[{id:"profile",label:"Profile",icon:"users"},{id:"account",label:"Account",icon:"settings"},{id:"connections",label:"Connections",icon:"link"},{id:"rpc",label:"RPC",icon:"globe"},{id:"privacy",label:"Privacy",icon:"shield"}];
export function UserSettingsTabs(){const [tab,setTab]=useState<Tab>("profile");const [profile,setProfile]=useState({displayName:"",avatarUrl:"",email:"",primaryRole:"CREATOR"});const [rpc,setRpc]=useState({customSolanaRpcUrl:"",customSolanaWsUrl:"",heliusApiKey:"",heliusApiKeyConfigured:false});const [message,setMessage]=useState<string|null>(null);const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:3010";const {currency,network}=useWalletPreferences();
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get("tab") as Tab|null;if(q&&tabs.some(x=>x.id===q))setTab(q);void fetch(`${api}/api/v1/users/me`,{credentials:"include"}).then(r=>r.ok?r.json():null).then(b=>{if(b?.data)setProfile({displayName:b.data.displayName||"",avatarUrl:b.data.avatarUrl||"",email:b.data.email||"",primaryRole:b.data.primaryRole||"CREATOR"})});void fetch(`${api}/api/v1/users/rpc-settings`,{credentials:"include"}).then(r=>r.ok?r.json():null).then(b=>{if(b?.data)setRpc(x=>({...x,customSolanaRpcUrl:b.data.customSolanaRpcUrl||"",customSolanaWsUrl:b.data.customSolanaWsUrl||"",heliusApiKeyConfigured:!!b.data.heliusApiKeyConfigured}))});},[api]);
 const title=useMemo(()=>tabs.find(x=>x.id===tab)?.label||"Settings",[tab]);async function saveProfile(e:FormEvent){e.preventDefault();setMessage(null);const r=await fetch(`${api}/api/v1/users/me`,{method:"PATCH",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:profile.displayName,avatarUrl:profile.avatarUrl||null})});setMessage(r.ok?"Profile saved.":"Profile could not be saved.");}
 async function saveRpc(e:FormEvent){e.preventDefault();setMessage(null);const r=await fetch(`${api}/api/v1/users/rpc-settings`,{method:"PATCH",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({customSolanaRpcUrl:rpc.customSolanaRpcUrl||null,customSolanaWsUrl:rpc.customSolanaWsUrl||null,...(rpc.heliusApiKey?{heliusApiKey:rpc.heliusApiKey}:{})})});const b=await r.json().catch(()=>null);setMessage(r.ok?"RPC settings saved. Helius keys are encrypted server-side.":b?.error?.message||"RPC settings could not be saved.");}
 async function deleteAccount(){const confirmation=window.prompt('Type DELETE MY ACCOUNT to continue.');if(confirmation!=="DELETE MY ACCOUNT")return;const r=await fetch(`${api}/api/v1/users/me`,{method:"DELETE",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation})});if(r.ok)window.location.assign(process.env.NEXT_PUBLIC_WEB_URL||"http://localhost:3000");else setMessage("Account deletion request failed.");}
 return <div><div className="flex gap-2 overflow-x-auto pb-2">{tabs.map(item=><button key={item.id} onClick={()=>setTab(item.id)} className={`inline-flex h-10 shrink-0 items-center gap-2 rounded-xl px-3 text-sm font-bold ${tab===item.id?"bg-emerald-950 text-white":"border border-neutral-200 bg-white text-neutral-600 dark:border-neutral-800 dark:bg-neutral-950 dark:text-neutral-300"}`}><Icon name={item.icon}/>{item.label}</button>)}</div><Card className="mt-4 p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-xs text-neutral-500">User-specific settings apply only to your account unless explicitly marked organization-wide.</p></div><StatusBadge>{profile.primaryRole}</StatusBadge></div>
 {tab==="profile"?<form onSubmit={saveProfile} className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-semibold">Display name<Input value={profile.displayName} onChange={e=>setProfile(x=>({...x,displayName:e.target.value}))}/></label><label className="grid gap-2 text-sm font-semibold">Avatar URL<Input value={profile.avatarUrl} onChange={e=>setProfile(x=>({...x,avatarUrl:e.target.value}))} placeholder="https://…"/></label><div className="rounded-xl bg-neutral-50 p-4 text-xs text-neutral-500 dark:bg-neutral-900">Company/foundation legal details and social links are managed separately so personal and organization identity do not get mixed.</div><div className="flex flex-wrap gap-2"><Button type="submit">Save profile</Button><a href="/settings/company" className="inline-flex h-10 items-center rounded-xl border border-neutral-200 px-4 text-sm font-bold dark:border-neutral-800">Company details</a></div></form>:null}
 {tab==="account"?<div className="mt-6 grid gap-4"><div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="text-xs text-neutral-400">Signed-in email</div><div className="mt-1 font-semibold">{profile.email||"—"}</div></div><a href="/sessions" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-950 dark:text-emerald-300">Manage active sessions <Icon name="arrow-right"/></a><Button className="w-fit bg-red-700 hover:bg-red-800" onClick={()=>void deleteAccount()}>Delete account</Button><p className="text-[11px] leading-5 text-neutral-500">Deletion revokes active sessions and queues profile data for deletion/anonymization where permitted. Required financial, audit and compliance records remain retained.</p></div>:null}
 {tab==="connections"?<div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="font-bold">Display currency</div><div className="mt-1 text-sm text-neutral-500">{currency} · default USD</div></div><div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="font-bold">Solana network</div><div className="mt-1 text-sm text-neutral-500">{network}</div></div><a href="/wallet" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-950 dark:text-emerald-300">Wallet connections <Icon name="arrow-right"/></a></div>:null}
 {tab==="rpc"?<form onSubmit={saveRpc} className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-semibold">Custom Solana RPC<Input value={rpc.customSolanaRpcUrl} onChange={e=>setRpc(x=>({...x,customSolanaRpcUrl:e.target.value}))} placeholder="https://your-rpc.example"/></label><label className="grid gap-2 text-sm font-semibold">Custom WebSocket RPC<Input value={rpc.customSolanaWsUrl} onChange={e=>setRpc(x=>({...x,customSolanaWsUrl:e.target.value}))} placeholder="wss://your-rpc.example"/></label><label className="grid gap-2 text-sm font-semibold">Helius API key<Input type="password" value={rpc.heliusApiKey} onChange={e=>setRpc(x=>({...x,heliusApiKey:e.target.value}))} placeholder={rpc.heliusApiKeyConfigured?"Configured · enter a new key to replace":"Enter key"}/></label><p className="text-[11px] leading-5 text-neutral-500">Private Helius keys are encrypted before database storage and are never returned by the API. Public RPC fallback remains available for development but should not be treated as production capacity.</p><Button type="submit" className="w-fit">Save RPC settings</Button></form>:null}
 {tab==="privacy"?<div className="mt-6 grid gap-4"><div className="rounded-xl bg-neutral-50 p-4 text-sm leading-6 text-neutral-600 dark:bg-neutral-900 dark:text-neutral-300"><b>Remember me</b> is opt-in. When selected, the session may last up to 27 days. PowerChain does not store your raw IP through this feature; optional security fingerprints are one-way keyed hashes when configured.</div><a href="/sessions" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-950 dark:text-emerald-300">Review sessions <Icon name="arrow-right"/></a></div>:null}
 {message?<div className="mt-5 rounded-xl border border-neutral-200 bg-neutral-50 p-3 text-xs text-neutral-600 dark:border-neutral-800 dark:bg-neutral-900 dark:text-neutral-300">{message}</div>:null}</Card></div>}
