export const DOMAIN_EVENTS = [
  "campaign.created",
  "campaign.published",
  "campaign.suspended",
  "payment.created",
  "payment.submitted",
  "payment.settlement.observed",
  "payment.reconciled",
  "donation.confirmed",
  "treasury.disbursement.created",
  "treasury.disbursement.confirmed",
  "milestone.completed",
  "evidence.submitted",
  "evidence.verified",
  "identity.check.submitted",
  "identity.check.verified",
  "business.verified",
  "agreement.created",
  "agreement.signature.requested",
  "agreement.signed",
  "escrow.tranche.approved",
  "escrow.tranche.released",
  "notification.queued",
  "notification.sent",
  "moderation.report.created",
  "moderation.resource.suspended",
] as const;

export type DomainEventName = (typeof DOMAIN_EVENTS)[number];
export interface DomainEvent<T = unknown> { id: string; type: DomainEventName; occurredAt: string; data: T }
