import { AppShell, Card, Section, StatusBadge } from "@powerchain/ui";

export function MarketingHome() {
  return <AppShell appName="Crowdfunding Infrastructure" nav={[{label:"Explore projects",href:"http://localhost:3001/explore"},{label:"How it works",href:"/how-it-works"},{label:"About",href:"/about"},{label:"Docs",href:"http://localhost:3008"},{label:"Sign in",href:"/auth/login"}]}>
    <div className="grid gap-10 py-8 lg:grid-cols-[1.12fr_.88fr] lg:py-16">
      <div className="flex flex-col justify-center"><StatusBadge tone="success">Humanitarian · disaster relief · renewables · public good</StatusBadge><h1 className="mt-5 max-w-4xl text-5xl font-bold tracking-tight md:text-6xl">Fund the mission. Verify what happens next.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">PowerChain connects campaign goals, bank and wallet payments, policy-controlled treasuries, milestone evidence and public impact into one accountable funding lifecycle.</p><div className="mt-7 flex flex-wrap gap-3"><a href="http://localhost:3001/explore" className="rounded-xl bg-emerald-950 px-5 py-3 text-sm font-bold text-white">Explore projects</a><a href="http://localhost:3001/create" className="rounded-xl border bg-white px-5 py-3 text-sm font-bold">Create campaign</a><a href="/auth/login" className="rounded-xl border bg-white px-5 py-3 text-sm font-bold">Sign in</a></div></div>
      <Card className="p-6 lg:p-8"><div className="text-sm font-semibold text-slate-500">Accountable funding lifecycle</div><div className="mt-5 space-y-3">{["Campaign goal","SEPA / wallet contribution","Verified on-chain settlement","Policy-controlled treasury","Milestone evidence review","Multisig disbursement","Impact + public audit"].map((item,index)=><div key={item} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-950 text-xs font-bold text-white">{index+1}</span><span className="text-sm font-medium">{item}</span></div>)}</div></Card>
    </div>
    <Section title="Built for accountable funding" description="The supporter journey stays simple while financial controls become more visible after payment."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Bank-first EUR","SEPA and SEPA Instant can feed EURe settlement into campaign treasury infrastructure."],["Humanitarian response","Emergency campaigns can publish needs, milestones, evidence and disbursements."],["Renewable projects","Solar, microgrid and clean-energy campaigns can gate releases against procurement and installation milestones."],["Soft tokenization","Optional attestations can recognize support without creating financial or profit-sharing rights."]].map(([title,copy])=><Card key={title} className="p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></Card>)}</div></Section>
  </AppShell>;
}
